#!/usr/bin/env bash
# Fixing container in 7 lines or less
sudo pkill -f apache2
sudo chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
