#!/usr/bin/env bash
# Configures a server using a bash script such that nginx is active and listening
# on port 80 of all server'sactive IPv4 IPs
sudo sed -i s/8080/80/ /etc/nginx/sites-enabled/default
sudo service nginx restart
